### PR TITLE
Update index.qmd

### PR DESCRIPTION
**Pull request by salbalkus**
add my date

### CODE REVIEW

**Comment by nhejazi** [comment]
thanks; almost didn’t see this so feel free to push directly and/or tag me next time

**Comment by salbalkus** [comment]
Thanks! At the time I didn't have permission to push directly; not sure if I do now.

**Comment by salbalkus** [comment]
Also question: does code need to be run for this? I thought I could just quickly edit the page on GitHub but it looks like the update isn't appearing for me.

**Comment by nhejazi** [comment]
i'm not exactly sure how permissions in organizations work but we should make sure that you can push directly. re: your question: the site should build automatically via actions (https://github.com/nshlab/labmeeting/blob/main/.github/workflows/publish.yml), but it looks like this hadn't been set to do so on PR, only on push

**Pull request merged**
